/* eslint-disable */
//tag color
const tagcolors = {
    "language": "red",
    "parody": "#3D7878",
    "character": "#9F0050",
    "group": "green",
    "artist": "blue",
    "female": "darkblue",
    "male": "purple",
    "misc": "black",
    "reclass": "#804040"
};
//language Icon
const lanIcon = {
    jp: `chrome-extension://${chrome.runtime.id}/res/lanIcon/jp.png`,
    "language:korean": `chrome-extension://${chrome.runtime.id}/res/lanIcon/kr.png`,
    "language:chinese": `chrome-extension://${chrome.runtime.id}/res/lanIcon/cn.png`,
    "language:english": `chrome-extension://${chrome.runtime.id}/res/lanIcon/en.png`,
    "language:dutch": `chrome-extension://${chrome.runtime.id}/res/lanIcon/netherlands.png`,
    "language:french": `chrome-extension://${chrome.runtime.id}/res/lanIcon/france.png`,
    "language:german": `chrome-extension://${chrome.runtime.id}/res/lanIcon/germany.png`,
    "language:hungarian": `chrome-extension://${chrome.runtime.id}/res/lanIcon/hungary.png`,
    "language:italian": `chrome-extension://${chrome.runtime.id}/res/lanIcon/italy.png`,
    "language:polish": `chrome-extension://${chrome.runtime.id}/res/lanIcon/poland.png`,
    "language:portuguese": `chrome-extension://${chrome.runtime.id}/res/lanIcon/portugal.png`,
    "language:russian": `chrome-extension://${chrome.runtime.id}/res/lanIcon/russia.png`,
    "language:spanish": `chrome-extension://${chrome.runtime.id}/res/lanIcon/spain.png`,
    "language:thai": `chrome-extension://${chrome.runtime.id}/res/lanIcon/thai.png`,
    "language:vietnamese": `chrome-extension://${chrome.runtime.id}/res/lanIcon/vietnam.png`
};
// translate
const tData={
    "=Age=":"=年齡=",//==========================================
    "age progression":"快速成長",
    "age regression":"返老還童",
    "dilf":"熟男",
    "infantilism":"幼稚病",
    "lolicon":"蘿莉控",
    "low lolicon":"隱晦的蘿莉控",
    "low shotacon":"隱晦的正太控",
    "low toddlercon":"隱晦的嬰兒控",
    "milf":"熟女",
    "old lady":"老女人",
    "old man":"老男人",
    "shotacon":"正太控",
    "toddlercon":"嬰兒控",
    "=Body=":"=身體=",//==========================================
    "amputee":"人棍",
    "body modification":"身體改造",
    "conjoined":"連體",
    "doll joints":"球形關節",
    "gijinka":"擬人化",
    "inflation":"脹腹",
    "invisible":"透明人",
    "muscle":"筋肉人",
    "multiple arms":"多個胳膊",
    "multiple breasts":"多個乳房",
    "multiple paizuri":"多人乳交",
    "multiple penises":"多根陰莖",
    "pregnant":"孕婦Play",
    "stretching":"擴張",
    "tailjob":"用尾巴擼",
    "wings":"翅膀",
    "=Change=":"=變化=",//==========================================
    "absorption":"吞噬吸收",
    "ass expansion":"屁股膨大",
    "balls expansion":"睾丸膨大",
    "body swap":"身體交換",
    "breast expansion":"乳房膨大",
    "clit growth":"陰蒂增長",
    "corruption":"墮落",
    "dick growth":"陰莖增長",
    "feminization":"男變女",
    "gender bender":"性別變化",
    "growth":"體型增大",
    "moral degeneration":"道德淪喪",
    "muscle growth":"肌肉增長",
    "nipple expansion":"乳頭膨大",
    "petrification":"石化",
    "shrinking":"體型縮小",
    "transformation":"身體變化",
    "weight gain":"體重增長",
    "=Creature=":"=生物=",//==========================================
    "alien":"外星人",
    "alien girl":"外星女",
    "angel":"天使",
    "bee girl":"蜂娘",
    "bunny boy":"兔男",
    "bunny girl":"兔娘",
    "catboy":"貓男",
    "catgirl":"貓娘",
    "cowgirl":"奶牛娘",
    "cowman":"奶牛男",
    "demon":"惡魔",
    "demon girl":"女惡魔",
    "dog boy":"犬男",
    "dog girl":"犬娘",
    "draenei":"德萊尼",
    "fairy":"妖精",
    "fox boy":"狐男",
    "fox girl":"狐娘",
    "furry":"人型獸",
    "ghost":"幽靈",
    "goblin":"地精",
    "harpy":"鳥身女妖",
    "horse boy":"馬男",
    "horse girl":"馬娘",
    "human on furry":"人X人性獸",
    "insect boy":"昆蟲男",
    "insect girl":"昆蟲娘",
    "kappa":"河童",
    "lizard girl":"蜥蜴娘",
    "lizard guy":"蜥蜴男",
    "mermaid":"人魚娘",
    "merman":"人魚男",
    "minotaur":"牛頭人",
    "monster":"怪物",
    "monster girl":"怪物娘",
    "mouse boy":"鼠男",
    "mouse girl":"鼠娘",
    "necrophilia":"奸屍",
    "oni":"日本鬼",
    "orc":"獸人",
    "pig girl":"豬娘",
    "pig man":"豬男",
    "plant girl":"植物娘",
    "plant guy":"植物男",
    "centaur":"半人馬",
    "raccoon boy":"浣熊男孩",
    "raccoon girl":"浣熊娘",//ehWiki
    "robot":"機器人",
    "robot girl":"機器娘",
    "sheep boy":"男羊人",
    "sheep girl":"綿羊娘",
    "slime":"史萊姆",
    "slime boy":"史萊姆男",//ehWiki
    "slime girl":"史萊姆娘",
    "snake girl":"蛇女",
    "snake guy":"男蛇人",
    "spider girl":"蜘蛛娘",
    "squid girl":"魷魚娘",
    "tentacles":"觸手",
    "wolf boy":"男狼人",
    "wolf girl":"狼女",
    "yukkuri":"油庫裡",
    "zombie":"喪屍",
    "=Animal=":"=動物=",//==========================================
    "animal on animal":"動物X動物",
    "animal on furry":"人型獸X動物",
    "bear":"熊",
    "bestiality":"獸交",
    "bull":"公牛",
    "camel":"駱駝",
    "cat":"貓",
    "cow":"牛",
    "crab":"蟹",
    "dinosaur":"恐龍",
    "dog":"犬",
    "dolphin":"海豚",
    "donkey":"毛驢",
    "dragon":"龍",
    "eel":"鰻魚",
    "elephant":"大象",
    "fish":"魚",
    "fox":"狐狸",
    "frog":"青蛙",
    "goat":"山羊",
    "gorilla":"猩猩",
    "horse":"馬",
    "insect":"昆蟲",
    "lion":"獅子",
    "lioness":"母獅",
    "low bestiality":"隱晦的獸交",
    "maggot":"蛆蟲",
    "monkey":"猴子",
    "mouse":"老鼠",
    "octopus":"章魚",
    "ostrich":"鴕鳥",
    "panther":"豹子",
    "pig":"豬",
    "rabbit":"兔子",
    "reptile":"爬行",
    "rhinoceros":"犀牛",
    "sheep":"羊",
    "shark":"鯊魚",
    "slug":"蛞蝓",
    "snake":"蛇",
    "spider":"蜘蛛",
    "tiger":"老虎",
    "turtle":"烏龜",
    "unicorn":"獨角獸",
    "whale":"鯨魚",
    "wolf":"狼",
    "worm":"蟲子",
    "zebra":"斑馬",
    "=Height=":"=身高=",//==========================================
    "giant":"巨人",
    "giantess":"女巨人",
    "midget":"侏儒",
    "minigirl":"袖珍女人",
    "miniguy":"袖珍男人",
    "tall girl":"高個女",
    "tall man":"高個男",
    "=Skin=":"=皮膚=",//==========================================
    "albino":"白化",
    "body writing":"身上寫字",
    "body painting":"人體彩繪",
    "dark skin":"黑皮膚",
    "freckles":"雀斑",
    "full body tattoo":"全身紋身",
    "gyaru":"太妹",
    "gyaru-oh":"馬仔",
    "oil":"抹油",
    "scar":"傷疤",
    "skinsuit":"人皮衣",
    "sweating":"出汗",
    "tanlines":"日曬線",
    "=Weight=":"=體重=",//==========================================
    "anorexic":"骨瘦如柴",
    "bbm":"胖帥男",
    "bbw":"胖美女",
    "=Head=":"=頭部=",//==========================================
    "ahegao":"阿嘿顏",
    "brain fuck":"腦交",
    "cockslapping":"陰莖蹭臉",
    "ear fuck":"耳交",
    "elf":"小精靈",
    "facesitting":"顏面騎乘",
    "gasmask":"防毒面具",
    "hairjob":"發交",
    "masked face":"戴面具",
    "prehensile hair":"抓著頭髮",
    "=Mind=":"=心靈=",//==========================================
    "chloroform":"迷藥",
    "drugs":"沉浸藥物",
    "drunk":"醉酒",
    "emotionless sex":"無感情性交",
    "mind break":"精神崩潰",
    "mind control":"思想控制",
    "parasite":"寄生",
    "possession":"佔據",
    "shared senses":"感官共用",
    "sleeping":"睡奸",
    "=Eyes=":"=眼睛=",//==========================================
    "blindfold":"遮眼",
    "cum in eye":"眼射",
    "eye penetration":"眼交",
    "eyemask":"眼部面具",
    "eyepatch":"眼罩",
    "glasses":"眼鏡",
    "sunglasses":"太陽鏡",
    "unusual pupils":"非正常瞳孔",
    "=Nose=":"=鼻子=",//==========================================
    "nose fuck":"鼻交",
    "nose hook":"鼻鉤",
    "smell":"聞味道",
    "=Mouth=":"=嘴部=",//==========================================
    "autofellatio":"自己口交",
    "ball sucking":"吸奶子",
    "big lips":"大嘴唇",
    "blowjob":"口交",
    "blowjob face":"口交臉",
    "braces":"牙套",
    "burping":"打嗝",
    "coprophagia":"食糞",
    "cunnilingus":"舔陰",
    "deepthroat":"深喉",
    "double blowjob":"兩女一屌",
    "foot licking":"舔足",
    "gag":"堵嘴",
    "gokkun":"飲精",
    "kissing":"接吻",
    "long tongue":"長舌頭",
    "piss drinking":"喝尿",
    "rimjob":"舔菊花",
    "saliva":"唾液",
    "smoking":"吸煙",
    "tooth brushing":"刷牙",
    "unusual teeth":"牙型奇異",
    "vampire":"吸血鬼",
    "vomit":"嘔吐",
    "vore":"丸吞",
    "=Neck=":"=脖子=",//==========================================
    "asphyxiation":"窒息",
    "collar":"項圈",
    "=Arms=":"=手臂=",//==========================================
    "armpit licking":"舔腋下",
    "armpit sex":"腋下交",
    "fingering":"指奸",
    "fisting":"拳交",
    "handjob":"套弄雞雞",
    "hairy armpits":"腋下多毛",
    "=Chest=":"=胸部=",//==========================================
    "=Breasts=":"=乳房=",//==========================================
    "autopaizuri":"自己乳交",
    "big areolae":"大乳暈",
    "big breasts":"巨乳",
    "breast feeding":"母乳餵養",
    "breast reduction":"乳房縮小",
    "huge breasts":"超巨乳",
    "lactation":"乳汁",
    "milking":"噴奶",
    "motorboating":"埋胸",
    "oppai loli":"巨乳蘿莉",
    "paizuri":"乳交",
    "small breasts":"貧乳",
    "=Nipples=":"=乳頭=",//==========================================
    "big nipples":"大乳頭",
    "dark nipples":"黑乳頭",
    "dicknipples":"雞巴乳頭",
    "inverted nipples":"乳頭內翻",
    "nipple fuck":"肏乳頭",
    "=Torso=":"=軀幹=",//=========================================
    "navel fuck":"肏肚臍",
    "stomach deformation":"胃變形",
    "=Lower Body=":"=下身=",//==========================================
    "=Crotch=":"=襠部=",//==========================================
    "bike shorts":"自行車短褲",
    "bloomers":"運動短褲",
    "chastity belt":"貞操帶",
    "diaper":"尿布",
    "fundoshi":"兜襠布",
    "gymshorts":"拳擊短褲",
    "hairy":"多陰毛",
    "pubic stubble":"陰毛茬",
    "shimapan":"條紋內褲",
    "urethra insertion":"尿道插入",
    "=Penile=":"=屌=",//==========================================
    "balljob":"睾丸交",
    "big balls":"大睾丸",
    "big penis":"大陰莖",
    "cbt":"虐睾丸",
    "cuntboy":"有屄的男人",
    "frottage":"雙屌互蹭",
    "futanari":"扶她",
    "futanari on male":"扶她X男人",
    "horse cock":"馬屌",
    "huge penis":"超大陰莖",
    "penis birth":"長出陰莖",
    "phimosis":"包莖",
    "prostate massage":"前列腺按摩",
    "shemale":"人妖",
    "scrotal lingerie":"陰囊內衣",
    "smegma":"包皮垢",
    "=Vaginal=":"=屄=",//==========================================
    "big clit":"大陰蒂",
    "big vagina":"大陰道",
    "birth":"出產",
    "cervix penetration":"子宮脫出",
    "defloration":"破處",
    "double vaginal":"兩屌一屄",
    "squirting":"潮吹",
    "strap-on":"假陽具",
    "tribadism":"兩屄互蹭",
    "triple vaginal":"三屌一屄",
    "vaginal sticker":"小穴貼",
    "=Buttocks=":"=臀部=",//==========================================
    "anal":"肛交",
    "anal birth":"肛門出產",
    "assjob":"肏屁股",
    "big ass":"大屁股",
    "double anal":"兩屌一菊",
    "enema":"灌腸",
    "farting":"放屁",
    "pegging":"女攻男受",
    "scat":"排糞Play",
    "spanking":"打屁股",
    "triple anal":"三屌一菊花",
    "=Either Hole=":"=各個穴=",//==========================================
    "eggs":"產蛋",
    "gaping":"豁開",
    "large insertions":"巨物插入",
    "nakadashi":"中出",
    "prolapse":"脫垂",
    "sex toys":"性玩具",
    "speculum":"內窺器",
    "unbirth":"鑽進屄裡",
    "=Legs=":"=腿部=",//==========================================
    "garter belt":"吊襪腰帶",
    "kneepit sex":"膝交",
    "leg lock":"夾腿",
    "pantyhose":"連褲襪",
    "stockings":"絲襪",
    "sumata":"素股",
    "=Feet=":"=腳部=",//==========================================
    "foot insertion":"腳入屄",
    "footjob":"足交",
    "thigh high boots":"過膝長靴",
    "=Costume=":"=服飾=",//==========================================
    "apron":"圍裙",
    "bandages":"繃帶",
    "bikini":"比基尼",
    "bodystocking":"連身襪",
    "bodysuit":"緊身衣",
    "bride":"新娘",
    "business suit":"商務裝",
    "butler":"男管家",
    "cashier":"收銀員",
    "cheerleader":"啦啦隊",
    "chinese dress":"中式服裝",
    "christmas":"聖誕裝",
    "condom":"避孕套",
    "corset":"緊身胸衣",
    "cosplaying":"Cos裝",
    "crossdressing":"異性服裝",
    "dougi":"武道服",
    "gothic lolita":"哥特洛麗塔",
    "haigure":"高叉馬步",
    "hijab":"頭巾",
    "kigurumi":"玩偶服",
    "kimono":"和服",
    "kunoichi":"女忍者",
    "lab coat":"白大褂",
    "latex":"乳膠衣",
    "leotard":"連體衣",
    "lingerie":"內衣",
    "living clothes":"觸手服",
    "magical girl":"魔法少女",
    "maid":"女僕",
    "mecha boy":"機甲男",//ehWiki
    "mecha girl":"機甲娘",
    "metal armor":"金屬盔甲",
    "miko":"日本巫女",
    "military":"軍裝",
    "nazi":"納粹",
    "ninja":"忍者",
    "nurse":"護士",
    "pantyjob":"肏內褲",
    "pasties":"乳貼",
    "piercing":"穿孔",
    "policeman":"男員警",
    "policewoman":"女員警",
    "ponygirl":"女騎師",
    "race queen":"賽車女郎",
    "randoseru":"日式小學書包",
    "schoolboy uniform":"男校服",
    "schoolgirl uniform":"女校服",
    "schoolboy":"男學生",
    "schoolgirl":"女學生",
    "stewardess":"制服",
    "swimsuit":"泳裝",
    "school swimsuit":"學校泳裝",
    "tights":"緊身服",
    "tracksuit":"運動服",
    "witch":"美式女巫",
    "=Multiple Activities=":"=多人活動=",//==========================================
    "ffm threesome":"兩女一男",
    "fft threesome":"兩女一扶她",
    "group":"群P",
    "harem":"後宮",
    "layer cake":"換著插",
    "mmf threesome":"兩男一女",
    "mmt threesome":"兩男一扶她",
    "mtf threesome":"一男一女一扶她",
    "ttf threesome":"兩扶她一女",
    "ttm threesome":"兩扶她一男",
    "twins":"雙胞胎",
    "=Multiple Holes=":"=多個穴=",//==========================================
    "all the way through":"頭尾貫通",
    "double penetration":"雙穴貫通",
    "triple penetration":"三穴貫通",
    "=Tools=":"=工具=",
    "dakimakura":"抱枕",
    "glory hole":"牆穴",
    "machine":"機械",
    "onahole":"自慰器",
    "pillory":"頸手枷",
    "pole dancing":"鋼管舞",
    "syringe":"注射器",
    "table masturbation":"桌子自慰",
    "tube":"插管",
    "whip":"鞭打",
    "wooden horse":"木馬",
    "wormhole":"蟲洞",
    "=Fluids=":"=流體=",//==========================================
    "underwater":"水下性愛",
    "=Bodily Fluids=":"=體液=",//==========================================
    "=Semen=":"=精液=",//==========================================
    "bukkake":"顏射",
    "cum bath":"精液浴",
    "cum swap":"交換精液",
    "=Waste=":"=排泄物=",//==========================================
    "blood":"血液",
    "menstruation":"經血",
    "public use":"公共使用",
    "urination":"排尿Play",
    "=Force=":"=能力=",//==========================================
    "chikan":"癡漢",
    "rape":"強姦",
    "time stop":"時間停止",
    "=Sadomasochism=":"=虐戀=",//==========================================
    "bdsm":"施虐受虐",
    "femdom":"女王",
    "forniphilia":"人型家居",
    "human cattle":"人型牲畜",
    "human pet":"人型寵物",
    "orgasm denial":"禁止高潮",
    "slave":"奴隸",
    "tickling":"瘙癢",
    "=Bondage=":"=束縛=",//==========================================
    "bondage":"捆綁",
    "shibari":"繩藝",
    "stuck in wall":"卡牆裡",
    "vacbed":"乳膠真空床",
    "=Violence=":"=暴力=",//==========================================
    "abortion":"墮胎",
    "cannibalism":"同類相食",
    "catfight":"兩女相爭",
    "guro":"獵奇",
    "electric shocks":"電擊",
    "ryona":"虐女萌",
    "snuff":"虐殺",
    "torture":"酷刑",
    "trampling":"踩踏",
    "wrestling":"摔跤",
    "=Self Pleasure=":"=自慰=",//==========================================
    "masturbation":"手淫",
    "phone sex":"電話性愛",
    "selfcest":"自己X自己",
    "solo action":"自慰",
    "=Disability=":"=殘疾=",//==========================================
    "blind":"瞎子",
    "handicapped":"殘疾",
    "mute":"啞巴",
    "=Gender=":"=性別=",//==========================================
    "=Inter-gender Relations=":"=跨性別=",//==========================================
    "futanari on futanari":"扶她X扶她",
    "male on futanari":"男人X扶她",
    "=Technical=":"=技術=",//==========================================
    "3d":"3D",
    "anaglyph":"立體",
    "animated":"動畫",
    "anthology":"選集",
    "artbook":"畫集",
    "figure":"畫像",
    "first person perspective":"第一人稱",
    "full color":"全彩",
    "game sprite":"圖元畫",
    "multi-work series":"故事系列",//ehWiki
    "novel":"小說",
    "paperchild":"紙孩",
    "redraw":"重繪",
    "screenshots":"截圖",
    "story arc":"故事框架",
    "tankoubon":"單行本",
    "themeless":"無題",
    "x-ray":"透視",
    "=Censorship=":"=色情審查=",//==========================================
    "full censorship":"色塊遮擋",
    "mosaic censorship":"馬賽克遮擋",
    "uncensored":"未審查",
    "=Cosplay=":"=Cosplay=",//==========================================
    "hardcore":"重口味",
    "non-nude":"非裸體",
    "=Expunging=":"=刪除=",//==========================================
    "already uploaded":"已上傳過",
    "compilation":"編輯",
    "forbidden content":"禁止的內容",
    "realporn":"真正的色情",
    "replaced":"已更換",
    "watermarked":"有浮水印",
    "=Semi-Expunging=":"=半成品=",//==========================================
    "incomplete":"不完整",
    "out of order":"次序顛倒",
    "missing cover":"無封面",
    "sample":"樣本",
    "scanmark":"掃描標記",
    "=Language=":"=語言=",//==========================================
    "albanian":"阿爾巴尼亞語",
    "arabic":"阿拉伯語",
    "caption":"自製標題",
    "catalan":"加泰羅尼亞語",
    "chinese":"中文",
    "czech":"捷克語",
    "danish":"丹麥語",
    "dutch":"荷蘭語",
    "english":"英語",
    "esperanto":"世界語",
    "estonian":"愛沙尼亞語",
    "finnish":"芬蘭語",
    "french":"法語",
    "german":"德語",
    "greek":"希臘語",
    "hebrew":"希伯來語",
    "hindi":"印地語",
    "hungarian":"匈牙利語",
    "indonesian":"西澳特羅尼西亞語",
    "italian":"義大利語",
    "japanese":"日語",
    "korean":"韓語",
    "malay":"馬來語",
    "polish":"波蘭語",
    "poor grammar":"語義不通",
    "portuguese":"葡萄牙語",
    "rewrite":"重新修改",
    "romanian":"羅馬尼亞語",
    "russian":"俄羅斯語",
    "slovak":"斯洛伐克語",
    "spanish":"西班牙語",
    "speechless":"無文字",
    "swedish":"瑞典語",
    "tagalog":"他加祿語",
    "text cleaned":"無嵌字版",
    "thai":"泰語",
    "translated":"翻譯",
    "turkish":"烏克蘭語",
    "ukrainian":"烏克蘭語",
    "vietnamese":"越南語",
    "=Contextual=":"=語境=",//==========================================
    "blackmail":"勒索",
    "cheating":"出軌",
    "coach":"教練",
    "females only":"只有女性",
    "males only":"只有男性",
    "impregnation":"內射",
    "netorare":"寢取",
    "prostitution":"賣淫",
    "swinging":"擺動",
    //======================================================================================================================
    "western":"西方人",
    "misc":"雜 項",
    "imageset":"圖片集",

    "softstar":"大宇資訊",
    //語言和色彩類
    "Italian":"義大利文",
    //同人題材類
    "touhou":"東方",
    "touhou project":"東方Project",
    "moetan":"萌單",
    "ore no imouto ga konna ni kawaii wake ga nai":	"我的妹妹不可能那麼可愛",
    "toaru kagaku no railgun":"某科學的超電磁炮",
    "kantai collection":"艦隊collection",
    "pokemon | pocket monsters":"精靈寶可夢",
    "higurashi no naku koro ni | when they cry":"寒蟬鳴泣之時",
    "saki":"天才麻將少女",
    "puella magi madoka magica":"魔法少女小圓",
    "lotte no omocha":"露蒂的玩具",
    "sword art online":"刀劍神域",
    "to love-ru":"To LOVE?",
    "ro-kyu-bu":"蘿球社",
    "tantei opera milky holmes":"偵探歌劇 少女福爾摩斯",
    "hyperdimension neptunia | choujigen game neptune":"超次元遊戲：海王星",
    "love live":"Love Live!",
    "sora no otoshimono | heavens lost property":"天降之物",
    "boku wa tomodachi ga sukunai":"我的朋友很少",
    "vocaloid":"V家",
    "date a live":"約會大作戰",
    "gochuumon wa usagi desu ka | is the order a rabbit":"今天你也要來點兔子嗎？",
    //角色
    "wriggle nightbug":"莉格露·奈特巴格",
    "mystia lorelei":"斯蒂婭·蘿蕾拉",
    "reimu hakurei":"博麗靈夢",
    "marisa kirisame":"霧雨魔理沙",
    "rumia":"露米婭",
    "cirno":"琪露諾",
    "daiyousei":"大妖精",
    "hong meiling":"紅美鈴",
    "patchouli knowledge":"帕秋莉‧諾蕾姬",
    "koakuma":"小惡魔",
    "sakuya izayoi":"十六夜咲夜",
    "remilia scarlet":"蕾米莉亞‧斯卡雷特",
    "flandre scarlet":"芙蘭朵露‧斯卡雷特",
    "letty whiterock":"蕾迪‧霍瓦特羅克",
    "chen":"橙",
    "ink nijihara":"虹原茵可",
    "pastel ink":"閃亮茵可",
    //外觀類
    "exhibitionism":"暴露狂",
    "yukata":"浴衣",
    "tiara":"頭飾",
    "crown":"皇冠",
    "hotpants":"緊身短褲",
    "sundress":"太陽裙(夏裝)",
    //年齡、職業或身份類
    "inseki":"姻親",
    "sister":"姐姐或妹妹",
    "mother":"母親",
    "father":"父親",
    "brother":"哥哥或弟弟",
    "niece":"侄女",
    "aunt":"阿姨",
    "uncle":"叔叔",
    "daughter":"女兒",
    "mature":"成熟的(通常指年紀較大的人)",
    "teacher":"教師",
    "princess":"公主",
    "nun":"修女",
    "interracial":"不同人種間的",
    "virginity":"處女",
    "school boy":"男學生",
    "cousin":"堂[表]兄弟姊妹",
    "tomboy":"女同假陽具(假小子)",
    "valkyrie":"女武神",
    "voyeurism":"窺陰癖者",
    "yandere":"病嬌",
    "tutor":"校外導師(家教)",
    "widower":"鰥夫",
    "widow":"寡婦",
    "tomgirl":"娘娘腔",

    //動作類
    "discipline":"調教",
    "filming":"拍攝",
    "grandmother":"老奶奶",
    "grandfather":"祖父",
    "granddaughter":"孫女",
    "dickgirl on dickgirl":"扶她上扶她",
    "male on dickgirl":"男的上扶她",
    "dickgirl on male":"扶她上男的",
    //類型類
    "incest":"亂倫",
    "yuri":"女同(GL)",
    "yaoi":"男同(BL)",
    "original":"原創",
    "wore":"丸吞",
    "absorb":"融合（皮類常用標籤）",
    "psssession":"佔據（皮類常用標籤）",
    "waiter":"服務員",
    "waitress":"女服務員",
    "leg locks":"腳鎖",
    "art book":"畫集",
    "girls only":"只有女的",
    "guys only":"只有男的",
    "doll":"玩偶",
    "gamecg":"遊戲CG",
    "sole male":"男角唯一",
    "sole female":"女角唯一",
    "netonare":"NTR綠帽子",
    "bunny ears":"兔耳",
    "humiliation":"淩辱",
    "sex addict":"性成癮",
    "bisexual":"雌雄同體或雙性戀",

    //重新分類
    "doujinshi":"同人本",
    "manga":"漫畫雜誌"
};